
AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-041feb57c611358bd"
      InstanceType: t2.micro 
      KeyName: ADS-KEYS      
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: 8
      Tags:
        - Key: Name
          Value: demo-ec2
        - Key: createdBy
          Value: DevOps Team
        
