 # This is a hands-on task to create the cloudformation stack with
# 2 EC2 instances in total & one s3 bucket
# Webserver with 8gb EBS Volume
# Appserver with 10gb EBS Volume
# One S3 bucket to store invoice pdf files

AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Parameters:
  WebserverAmiid:
    Description: The EC2 AMI id
    Type: String
    Default: ami-038937b3d6616035f

  WebserverInstancetype:
    Description: The EC2 Instance Type
    Type: String
    Default: t2.micro

  WebserverVolumesize:
    Description: The EC2 Volumesize
    Type: Number
    Default: 8

  AppserverAmiid:
    Description: The EC2 AMI id
    Type: String
    Default: ami-038937b3d6616035f

  AppserverInstancetype:
    Description: The EC2 Instance Type
    Type: String
    Default: t2.micro

  AppserverVolumesize:
    Description: The EC2 Volumesize
    Type: Number
    Default: 8

  S3bucketname:
    Description: The name of the S3 bucket
    Type: String


Resources:
  Webserver:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !Ref WebserverAmiid
      InstanceType: !Ref WebserverInstancetype      
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: !Ref WebserverVolumesize
  Appserver:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !Ref AppserverAmiid
      InstanceType: !Ref AppserverInstancetype
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: !Ref AppserverVolumesize
  
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3bucketname


 


Resources:
  Webserver:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-03f65b8614a860c29"
      InstanceType: t2.micro
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: 8
  Appserver:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-03f65b8614a860c29"
      InstanceType: t2.micro
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: 10
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Bucket: "jjtech-tower-joel-w-f-2"
      
        