# This is a hands-on task to create the cloudformation stack with
# 2 EC2 instances in total & one s3 bucket
# WebServer with 8gb EBS
# AppServer with 10gb EBS
# One s3 bucket to store invoice pds files

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: "t2.micro"
    Description: "Type of the EC2 instance to create"
  
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
       ImageId: "ami-041feb57c611358bd"
       InstanceType: !Ref InstanceTypeParameter
       KeyName: "ADS-KEYS"
       BlockDeviceMappings: 
       - DeviceName: "/dev/sdm"
         Ebs: 
          VolumeType: "io1"
          Iops: 100
          DeleteOnTermination: true
          VolumeSize: 8
  AppServer:
    Type: AWS::EC2::Instance
    Properties:
       ImageId: "ami-041feb57c611358bd"
       InstanceType: "t2.micro"
       KeyName: "ADS-KEYS"
       BlockDeviceMappings: 
       - DeviceName: "/dev/sdm"
         Ebs: 
          VolumeType: "io1"
          Iops: 100
          DeleteOnTermination: true
          VolumeSize: 10
  S3InvoiceBucket:
    Type: AWS::S3::Bucket 
    Properties:
       BucketName: "ami-041feb57c611358bd"  

  S3StorageBucket:
    Type: AWS::S3::Bucket # When you provide properties, cloud formation will give a default bucket name


